os: linux

dist: bionic

language: python

services:
    - docker

install:
    - docker build --build-arg PG_VERSION="${PG_VERSION}" --build-arg PYTHON_VERSION="${PYTHON_VERSION}" -t tests -f Dockerfile--${TEST_PLATFORM}.tmpl .

script:
    - docker run $(bash <(curl -s https://codecov.io/env)) -t tests

notifications:
    email:
        on_success: change
        on_failure: always

env:
    - TEST_PLATFORM=std2-all PYTHON_VERSION=3.8.0 PG_VERSION=17
    - TEST_PLATFORM=std2-all PYTHON_VERSION=3.8 PG_VERSION=17
    - TEST_PLATFORM=std2-all PYTHON_VERSION=3.9 PG_VERSION=17
    - TEST_PLATFORM=std2-all PYTHON_VERSION=3.10 PG_VERSION=17
    - TEST_PLATFORM=std2-all PYTHON_VERSION=3.11 PG_VERSION=17
    - TEST_PLATFORM=std PYTHON_VERSION=3 PG_VERSION=16
    - TEST_PLATFORM=std PYTHON_VERSION=3 PG_VERSION=15
    - TEST_PLATFORM=std PYTHON_VERSION=3 PG_VERSION=14
    - TEST_PLATFORM=std PYTHON_VERSION=3 PG_VERSION=13
    - TEST_PLATFORM=std PYTHON_VERSION=3 PG_VERSION=12
    - TEST_PLATFORM=std PYTHON_VERSION=3 PG_VERSION=11
    - TEST_PLATFORM=std PYTHON_VERSION=3 PG_VERSION=10
    - TEST_PLATFORM=std-all PYTHON_VERSION=3 PG_VERSION=17
    - TEST_PLATFORM=ubuntu_24_04 PYTHON_VERSION=3 PG_VERSION=17
    - TEST_PLATFORM=altlinux_10 PYTHON_VERSION=3 PG_VERSION=17
    - TEST_PLATFORM=altlinux_11 PYTHON_VERSION=3 PG_VERSION=17
