os: linux

dist: bionic

language: python

services:
    - docker

install:
    - ./mk_dockerfile.sh
    - docker-compose build

script:
    - docker-compose run $(bash <(curl -s https://codecov.io/env)) tests

notifications:
    email:
        on_success: change
        on_failure: always

env:
    - PYTHON_VERSION=3 PG_VERSION=14
    - PYTHON_VERSION=3 PG_VERSION=13
    - PYTHON_VERSION=3 PG_VERSION=12
    - PYTHON_VERSION=3 PG_VERSION=11
    - PYTHON_VERSION=3 PG_VERSION=10
#    - PYTHON_VERSION=3 PG_VERSION=9.6
#    - PYTHON_VERSION=3 PG_VERSION=9.5
#    - PYTHON_VERSION=3 PG_VERSION=9.4
#    - PYTHON_VERSION=2 PG_VERSION=10
#    - PYTHON_VERSION=2 PG_VERSION=9.6
#    - PYTHON_VERSION=2 PG_VERSION=9.5
#    - PYTHON_VERSION=2 PG_VERSION=9.4
